### PR TITLE
Update @mozilla-protocol/assets to 2.1.1 (#479)

### LINKED ISSUE #479: Update @mozilla-protocol/assets to 3.0.0
This will:

- Bring in the new logos for Browser, Beta, Dev Ed, and Nightly.
- Bring in logos for Monitor, Send, and Lockwise.
- Bring in the new icon designs added in https://github.com/mozilla/protocol-assets/pull/22
  - Note: this is a breaking change as:
    -  the `ui` folder is removed and those assets moved one level up
    - the social icons are now in `icons/social`
    - the Focus logo has been removed
    - all the logo files have moved and have new names

### PR DESCRIPTION
**Pull request by stephaniehobson**
## Description

Describe what this change does.

- ~I have documented this change in the design system.~
- [x] I have recorded this change in `CHANGELOG.md`.

### Issue

Fix #479

### Testing

- All icons that were inside the `ui` folder have been moved
- Background-size declarations have been added to places icons are used (new icon files are larger)
- Black icons no longer have `-black` in the file name.

### CODE REVIEW

**Comment by stephaniehobson** [comment]
@alexgibson Could you have a look at the package-lock file please? It added a bunch of stuff as "optional" when I ran the upgrade.

**Comment by alexgibson** [comment]
@stephaniehobson try updating the version of npm you have installed locally on your machine.

**Comment by stephaniehobson** [comment]
The package-lock file is co-operating now :)

This is ready for a general code review.

**Comment by stephaniehobson** [comment]
Closing this in favour of going straight to 3.0.0.

**Pull request closed without merging**
