### PR TITLE
Add direction toggle

### PR DESCRIPTION
**Pull request by craigcook**
## Description
Adds a LTR/RTL toggle to the theme to change the text direction of the component preview.

### CODE REVIEW

**Comment by craigcook** [comment]
This is only semi-functional at the moment. It works when you do a page refresh but not when you're navigating around the set because clicking links does some ajaxy stuff to change the content rather than actually loading the page, which means the toggle doesn't init. 

I think we may be able to piggy-back on the event that changes content around to init the toggle but that's beyond my skills with JS.

**Comment by alexgibson** [comment]
I opened a PR to your branch to fix the toggle

**Comment by craigcook** [comment]
Note, this also removes the padding from the component preview. I don't like how it looks without that bit of spacing around smaller components like single buttons, but it gives an unrealistic presentation of full-width components like Split. I think I may add a separate padded preview to use when needed but for now let's lose the spacing.

**Review by alexgibson — APPROVED** [review]
r+

**Pull request merged**
