### PR TITLE
Update to 7.0.0.

### PR DESCRIPTION
**Pull request by stephaniehobson**
## Description

Bumps version to 7.0.0.

- [x] I have documented this change in the design system.
- [x] I have recorded this change in `CHANGELOG.md`.

### CODE REVIEW

**Comment by alexgibson** [comment]
Changes look good, but I think if we rebase on master we can get https://github.com/mozilla/protocol/issues/380 into this release too?

**Comment by stephaniehobson** [comment]
Rebased.

**Comment by alexgibson** [comment]
This looks like it's not rebased yet, I don't see `Update product button theme color (#380)` in the changelog.

**Comment by stephaniehobson** [comment]
Actually pushed this time.

**Pull request merged**
