### PR TITLE
Add Webpack config for package publishing (Fixes #746)

### LINKED ISSUE #746: Create a standalone webpack config for compiling the Protocol NPM package
This can exist separately from whatever we use to build the docs.

Also needs to watch for changes on CSS/JS files and recompile when `mode=development`.

### PR DESCRIPTION
**Pull request by alexgibson**
## Description

This PR separates the code that builds the Protocol NPM package from the code that builds the documentation site. It adds a new Webpack configuration for building the NPM package, which now gets created in the `./package/` directory. The docs pages still get built to `./dist/` using the existing Gulp script (which can be replaced by Fractal later).

I've also updated the Protocol ESLint config, so it works better with the new structure.

- [x] I have documented this change in the design system.
- [x] I have recorded this change in `CHANGELOG.md`.

### Issue

#746
#753

### Testing

Demo site: https://demo2--mozilla-protocol.netlify.app/

- [x] Running `npm run build` should build the NPM package contents into the `./package/` directory.
- [x] The contents of the `./package/` directory should have the same files and structure as what gets published in the `./dist/assets/protocol/` directory on the current `master` branch.
- [x] Running `npm start` should build the docs as normal. 
- [x] Browsing around the docs site locally works as intended with no 404s or errors in the console.
- [x] Running `npm run test` builds the package, and linting and tests pass OK.

Pre-publish test run on bedrock:

- [x] Manually copy the contents of the `./package/` directory into `node_modules/@mozilla-protocol/core/protocol`, and verify that bedrock can be built sucessfully using the new package.

### CODE REVIEW

**Comment by alexgibson** [comment]
This is ready for review I think (but should probably be reviewed after https://github.com/mozilla/protocol/pull/752)

**Comment by craigcook** [comment]
Needs a rebase after #752 merged

**Comment by alexgibson** [comment]
Rebased

**Review by craigcook — APPROVED** [review]
📦

**Pull request merged**
