### PR TITLE
Bump version to 14.1.0

### PR DESCRIPTION
**Pull request by craigcook**

### CODE REVIEW

**Review by alexgibson — CHANGES_REQUESTED** [review]
I think you also need to bump the version number in https://github.com/mozilla/protocol/blob/main/src/assets/package/package.json

**Comment by craigcook** [comment]
> I think you also need to bump the version number in https://github.com/mozilla/protocol/blob/main/src/assets/package/package.json

D'oh, I knew I was forgetting something. Updated.

**Comment by alexgibson** [comment]
Sorry I missed this, there's also a version numnber in the readme that looks like it needs updating too https://github.com/mozilla/protocol/blob/main/src/assets/package/README.md

**Review by alexgibson — APPROVED** [review]
Looks good! 🩹

**Pull request merged**
