### PR TITLE
Bump version to 13.0.0

### PR DESCRIPTION
**Pull request by craigcook**
OMG THEMING HAS FINALLY LANDED 🎉 🥳 💥

### CODE REVIEW

**Comment by craigcook** [comment]
Actually let's hold on this for a moment and get assets updated first, then I'll include that update here. 
https://github.com/mozilla/protocol-assets/pull/50

**Comment by craigcook** [comment]
Updated to include protocol-assets 3.0.2

**Comment by stephaniehobson** [comment]
Please update the changelog with the protocol-asset bump. kthxbye

**Comment by craigcook** [comment]
D'oh! Changelog updated.

**Review by stephaniehobson — APPROVED** [review]
R+ 🌺

**Pull request merged**
