### PR TITLE
Update docs to clarify brand variable use (fixes #697)

### LINKED ISSUE #697: Update docs to clarify SCSS variable use
## Description

We experienced unexpected behaviour in the use of Protocol theming with Bedrock, due to the way Sass compiles variables. To avoid confusion in the future, we want to add a note for SCSS variables in the theming docs.

### PR DESCRIPTION
**Pull request by maureenlholland**
## Description

Adds small note to https://protocol.mozilla.org/fundamentals/themes.html documentation to explain how SCSS variables should work across multiple files.

- [x] I have recorded this change in `CHANGELOG.md`.

### Issue

https://github.com/mozilla/protocol/issues/697

### Testing

Check note is on correct page. Confirm clarity of note content.

### CODE REVIEW

**Review by alexgibson — APPROVED** [review]
This needs a rebase, but r+ on the change 👍

**Review by nathan-barrett — APPROVED** [review]
👍🏻

**Comment by maureenlholland** [comment]
@alexgibson I did a merge update out of habit, is that a problem for git history? Let me know if I should undo that and rebase instead.

**Review by reemhamz — APPROVED** [review]
Looks good to me!

**Comment by alexgibson** [comment]
@maureenlholland not a problem, I squashed the commits whilst merging 👍

**Pull request merged**
