### PR TITLE
Atomic heading utility classes (#297)

### PR DESCRIPTION
**Pull request by stephaniehobson**
## Description

Add atomic heading utility classes.

- [x] I have documented this change in the design system.
- [x] I have recorded this change in `CHANGELOG.md`.

### Issue

See #297

### CODE REVIEW

**Comment by craigcook** [comment]
OK, I'm gonna pick a fight...

While I acknowledge the pragmatic usefulness of presentational utility classes, I also don't think we should encourage them. I worry about baking a lot of presentation into the HTML by relying on a class that does nothing but set a font size. I'd rather treat titles as truly atomic components, like what KIND of title is this, not just what size it should be. 

Of course, as long as we're getting full-page designs with text sized arbitrarily, we might have to resort to this anyway. But I'm prepared to take that fight to the brand team and work on defining reusable title atoms. 🥊

**Comment by stephaniehobson** [comment]
I think this PR is still good as-is. One outstanding (but not blocking) [question from #297](https://github.com/mozilla/protocol/issues/297#issuecomment-501931689): 

> Now that I'm looking at it I really want to alias @mixin text-display-lg to @mixin text-title-lg. Would that increase or decrease confusion and muscle memory?

**Comment by stephaniehobson** [comment]
Oh, actually this needs documentation still 😅

**Comment by stephaniehobson** [comment]
Closing in favour of https://github.com/mozilla/protocol/pull/555.

**Pull request closed without merging**
