### PR TITLE
Refactored gulp to process assets for publishing to NPM

### PR DESCRIPTION
**Pull request by alexgibson**
- Process protocol and documentation assets separately:
  - Protocol assets are copied to `./dist/assets/protocol/{css|js}/`
  - Docs assets are copied to `./dist/assets/docs/{css|js}`
- Fix JS and CSS compression tasks (Fixes https://github.com/mozilla/protocol/issues/39).
- Makes sure unconcatenated JS files are copied over (Fixes https://github.com/mozilla/protocol/issues/38).
- Remove Bower support (Fixes https://github.com/mozilla/protocol/issues/24)

### CODE REVIEW

**Comment by alexgibson** [comment]
OK, after talking with Paul re: the bedrock side I have some small modifications I'd like to make. Putting this back to WIP for now until it's ready for review.

**Comment by michaelmccombie** [comment]
There was an error (that also exists in master) with the path referenced in the css:clean gulp task. So I made a commit on this branch to fix that. Other than that everything looks good so far. I'll take another look when you are finished making the modifications you discussed with Paul.

**Comment by alexgibson** [comment]
> There was an error (that also exists in master) with the path referenced in the css:clean gulp task. So I made a commit on this branch to fix that.

Thanks for the commit, but I think this is only part of the issue. The task works independently via `gulp css:clean`, but not when run as part of `gulp build`. I think the main issue is we're running a some tasks in parallel, which should be happening in serial. I'll see if I can try and fix it in this PR.

**Comment by alexgibson** [comment]
@michaelmccombie OK I think everything should be ready for review. I fixed both the JS and CSS compression tasks and made sure all tasks `return` their streams correctly, so they are guaranteed to excecute in order 👍

**Pull request merged**
