### PR TITLE
Split component - third pass

### LINKED ISSUE #326: Implement Split Component (replaces hero and feature)
- [x] Better name
- [x] parent container
  - [x] expands to fit minimum height of text or image content
- [x] fixed ratio content (image or video)
  - [x] can be on left or right
  - [x] image can be any size
  - [x] can be top, center, or bottom aligned to parent
    screen shot 2019-02-21 at 1 19 45 pm
  - [x] can be indented, fit, or overflow the container vertically
    screen shot 2019-02-21 at 1 19 31 pm
  - [x] can overflow the container horizontally
    screen shot 2019-02-21 at 1 27 36 pm
  - [x] can be set to take up half or two thirds (??? designers a little help here) of the parent container
    screen shot 2019-02-21 at 1 31 47 pm
- [x] flexible ratio content (text, headings, buttons)
  - [x] can be on left or right
  - [x] can be top, center, or bottom aligned to parent 
    screen shot 2019-02-21 at 1 20 03 pm

### PR DESCRIPTION
**Pull request by stephaniehobson**
- [x] RTL support
- [x] fallback support for non-grid browsers
- [x] finalize class names #356 
- [x] increase padding between sides at larger breakpoints
- [x] full support for `.l-reverse` 
- [x] change is-inverse to l-reverse
- [x] mobile support for flush and pop classes
- [x] class to hide the image on mobile only
- [x] overflow bug
- [ ] cross browser testing
- [ ] documentation

## Description

Adds a new component to replace hero, feature, and billboard.

- [ ] I have documented this change in the design system.
- [ ] I have recorded this change in `CHANGELOG.md`.

### Issue

Fix #326 

### Testing

- [ ] LTR
- [ ] backwards compatability

### CODE REVIEW

**Comment by stephaniehobson** [comment]
Note to self: see if this component can handle the trailhead designs on /accounts and /firefox/new

**Comment by stephaniehobson** [comment]
I think I need to re-factor a bit to allow this to be nested in a `mzp-l-content` wrapper.

**Comment by stephaniehobson** [comment]
Also, it's on demo if you want to see it in action: 
https://demo1--mozilla-protocol.netlify.com/demos/block.html
https://demo1--mozilla-protocol.netlify.com/demos/block-outlines.html

**Comment by stephaniehobson** [comment]
I expected us to have overflow-x:hidden on `body` but we don't. I assume it's for a good reason.
That means this component needs to safe guard against a crawl bar. I think that means it can't be nested in `mzp-l-content`.

**Comment by craigcook** [comment]
This is back up on demo1 for the moment, but one of the links changed so re-commenting here.

Regular examples: https://demo1--mozilla-protocol.netlify.app/demos/block.html
Fancy interactive demo: https://demo1--mozilla-protocol.netlify.app/demos/block-demo.html

**Pull request closed without merging**
